apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  security:
    controlPlane:
      mtls: true
    dataPlane:
      automtls: true
      mtls: true
  tracing:
    sampling: 10000
    type: Jaeger
  mode: MultiTenant
  profiles:
    - default
  gateways:
    openshiftRoute:
      enabled: false
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  version: v2.5
  telemetry:
    type: Istiod
